global using DrawingColor = System.Drawing.Color;
global using Microsoft.AspNetCore.Authentication.Cookies;
global using Microsoft.AspNetCore.Authentication;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc.Authorization;
global using Microsoft.AspNetCore.Mvc.Controllers;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.SignalR;
global using Microsoft.CodeAnalysis;
global using Microsoft.Data.SqlClient;
global using RepoDb.Attributes;
global using RepoDb;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Diagnostics;
global using System.Drawing;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Security.Claims;
global using System.Security.Principal;
global using System.Text.Json.Serialization;
global using System.Text.Json;
global using Microsoft.AspNetCore.Mvc.DataAnnotations;
global using Microsoft.Extensions.Localization;
global using Microsoft.AspNetCore.Http.Extensions;
using SKL.Data;
using SKL.Repositories.IRepository;
using SKL.Repositories;
using SKL.Services.IServices;
using SKL.Services;
using SKL.Models;
using SKL;