// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Action
{
    public int IdActions { get; set; }

    public string ActionName { get; set; }

    public int IdFase { get; set; }

    public int IdUsr { get; set; }

    public int IdAspect { get; set; }

    public DateTime ActionStartdate { get; set; }

    public DateTime ActionEnddate { get; set; }

    public virtual ICollection<Evidence> Evidences { get; set; } = new List<Evidence>();

    public virtual Aspect IdAspectNavigation { get; set; }

    public virtual Fase IdFaseNavigation { get; set; }

    public virtual Usuario IdUsrNavigation { get; set; }
}