// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Aspect
{
    public int IdAspects { get; set; }

    public string AspectsName { get; set; }

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();
}