// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Aspect
{
    [Map("id_aspect")]
    public int Id { get; set; }
    [Map("aspect_name")]
    public string Name { get; set; }

    public virtual ICollection<Tasks> Actions { get; set; } = new List<Tasks>();
}