// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Evidence
{
    public int IdEvidences { get; set; }

    public int IdAction { get; set; }

    public string Evidences { get; set; }

    public virtual Tasks IdActionNavigation { get; set; }
}