// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Evidence
{
    [Map("id_evidences")]
    public int IdEvidences { get; set; }
    [Map("id_task")]
    public int IdTask { get; set; }
    [Map("evidences")]
    public string Evidences { get; set; }

    public IEnumerable<Task> Task { get; set; }

}