// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Fase
{
    public int IdFase { get; set; }

    public string FaseName { get; set; }

    public DateTime FaseStartdate { get; set; }

    public DateTime FaseEnddate { get; set; }

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();
}