// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Fase
{
    [Map("id_fase")]
    public int Id { get; set; }
    [Map("fase_name")]
    public string Name { get; set; }
    [Map("fase_startdate")]
    public DateTime Start { get; set; }
    [Map("fase_enddate")]
    public DateTime End { get; set; }
    [Map("currentdate")]
    public DateTime CurrentDate { get; set; }

    

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();
}