// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Shift
{
    [Map("id_shift")]
    public int Id { get; set; }
    [Map("shift_name")]
    public string Name { get; set; }
    [Map("start")]
    public string Start { get; set; }
    [Map("end")]
    public string End { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; } = new List<Usuario>();
}