// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SKL.Models;

public partial class Usuario
{
    [Map("id_usr")]
    public int IdUsr { get; set; }
    [Map("name")]
    public string Name { get; set; }
    [Map("usr_name")]
    public string UsrName { get; set; }
    [Map("usr_pass")]
    public string UsrPass { get; set; }
    [Map("id_usr_type")]
    public int Role { get; set; }
    [Map("id_usr_position")]
    public int IdUsrPosition { get; set; }
    [Map("id_shift")]
    public int Shift { get; set; }
    [Map("id_usr_department")]
    public int IdUsrDepartment { get; set; }
    [Map("emp_no")]
    public int EmpNo { get; set; }
    [Map("date")]
    public DateTime Date { get; set; }
    [Map("usr_img")]
    public string UsrImg { get; set; }

    public virtual ICollection<Action> Actions { get; set; } = new List<Action>();

    public virtual Shift IdShiftNavigation { get; set; }

    public virtual Department IdUsrDepartmentNavigation { get; set; }

    public virtual Position IdUsrPositionNavigation { get; set; }

    public virtual UserType IdUsrTypeNavigation { get; set; }
}